"""Initial revision 1

Revision ID: 9f355e9a3a11
Revises: 
Create Date: 2024-09-24 11:44:15.660820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f355e9a3a11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='digital_hub_bot'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tg', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=320), nullable=False),
    sa.Column('fullname', sa.String(length=320), nullable=False),
    sa.Column('date_reg', sa.DateTime(), nullable=False),
    sa.Column('id_topic_chat', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='digital_hub_bot'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='digital_hub_bot')
    op.drop_table('admin_group', schema='digital_hub_bot')
    # ### end Alembic commands ###
